<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EU216N6" failures="1" tests="7" name="ShopizerAdmin.TestCase.UserManagement.UserManagementTest" time="212.727" errors="0" timestamp="2023-07-27T15:19:22 ICT" skipped="0">
  <testcase classname="ShopizerAdmin.TestCase.UserManagement.UserManagementTest" name="AddUserWithInvalidEmail" time="26.230"/>
  <system-out/>
  <testcase classname="ShopizerAdmin.TestCase.UserManagement.UserManagementTest" name="AddUserWithWrongPassword" time="31.139"/>
  <system-out/>
  <testcase classname="ShopizerAdmin.TestCase.UserManagement.UserManagementTest" name="AddUserTest" time="50.489"/>
  <system-out/>
  <testcase classname="ShopizerAdmin.TestCase.UserManagement.UserManagementTest" name="SearchByName" time="22.120"/>
  <system-out/>
  <testcase classname="ShopizerAdmin.TestCase.UserManagement.UserManagementTest" name="SearchByEmail" time="21.636"/>
  <system-out/>
  <testcase classname="ShopizerAdmin.TestCase.UserManagement.UserManagementTest" name="EditUser" time="21.439">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at ShopizerAdmin.Pages.UserManagementPage.UserManagementPage.UserEdit(UserManagementPage.java:152)
at ShopizerAdmin.TestCase.UserManagement.UserManagementTest.EditUser(UserManagementTest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- EditUser -->
  <system-out/>
  <testcase classname="ShopizerAdmin.TestCase.UserManagement.UserManagementTest" name="RemoveUser" time="39.674"/>
  <system-out/>
</testsuite> <!-- ShopizerAdmin.TestCase.UserManagement.UserManagementTest -->
